# Generated by Django 6.0.5 on 2026-06-01 18:43

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpDeskUser',
            fields=[
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='release_version',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
